### ISSUE TITLE
ReelController is not present in repository

### ISSUE THREAD

**Issue by mterczynski** [PrzemoProgrammer/Slot-Machine#1]
Is this intentional?

`code/client/src/game/machine/reel/Reel.ts` imports `"./controller/ReelController";` but there is no `controller` folder relative to `Reel.ts`

![image](https://github.com/user-attachments/assets/1c6dc762-20bc-46f5-bc2a-ae62e7aa8a15)

**Comment by PrzemoProgrammer** [comment]
This project is not fully open source

niedz., 25 sie 2024, 14:28 użytkownik Michał Terczyński <
***@***.***> napisał:
